### ISSUE TITLE
there maybe some bug about the train_gpt.py(https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/train_gpt.py)

### ISSUE THREAD

**Issue by lambda7xx** [hpcaitech/ColossalAI-Examples#196]
### 🐛 Describe the bug

I try to run a config by using the [train_gpt.py](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/train_gpt.py). I add a model on the [gpt.py](https://github.com/hpcaitech/Titans/blob/main/titans/model/gpt/gpt.py) .
```

def gpt2_test4gpu350M(**kwargs):
    model_kwargs = dict(hidden_size=1024, depth=24, num_heads=16,max_position_embeddings=2048, **kwargs)
    return _create_gpt_model(**model_kwargs)

```
And I change my dateset [webtext](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/dataset/webtext.py) to this .

```

@DATASETS.register_module
class  WebtextDataset(Dataset):

    def __init__(self, path=None, seq_len=1024, mbs = 4) -> None:
        super().__init__()
        if path is not None:
            root = os.path.dirname(path)
            encoded_data_cache_path = os.path.join(root, f'gpt_webtext_{seq_len}.pt')
        else:
            encoded_data_cache_path = f'gpt_webtext_{seq_len}.pt'

        self.data = torch.randint(0,10000,(seq_len, ), requires_grad=False, device=torch.device('cpu')).long()
        self.attention_mask = (torch.rand((seq_len, seq_len), requires_grad=False, device=torch.device('cpu')))
        self.attention_mask = torch.where(self.attention_mask < 0.5, 0, 1)
        print("self.atttntion_mask:",self.attention_mask[:20])
        
        self.mbs =mbs 
        print("self.mbs:",self.mbs)

        torch.save((seq_len, self.data, self.attention_mask), encoded_data_cache_path)

    def __len__(self):
        print("WebtextDataset,self.mbs*3:",self.mbs) ## len(train_loader) ：返回的是len(dataset)/batch_size
        return self.mbs * 5

    def __getitem__(self, index):
        return {'input_ids':self.data,
            'attention_mask': self.attention_mask[0]}, self.data

```
I run this model and colossalai just spends 1s for 1 iteration. But I run the same model on Megatron-LM and I need about 100s for one iteration.

**Comment by lambda7xx** [comment]
> ### 🐛 Describe the bug
> I try to run a config by using the [train_gpt.py](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/train_gpt.py). I add a model on the [gpt.py](https://github.com/hpcaitech/Titans/blob/main/titans/model/gpt/gpt.py) .
> 
> ```
> 
> def gpt2_test4gpu350M(**kwargs):
>     model_kwargs = dict(hidden_size=1024, depth=24, num_heads=16,max_position_embeddings=2048, **kwargs)
>     return _create_gpt_model(**model_kwargs)
> ```
> 
> And I change my dateset [webtext](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/dataset/webtext.py) to this .
> 
> ```
> 
> @DATASETS.register_module
> class  WebtextDataset(Dataset):
> 
>     def __init__(self, path=None, seq_len=1024, mbs = 4) -> None:
>         super().__init__()
>         if path is not None:
>             root = os.path.dirname(path)
>             encoded_data_cache_path = os.path.join(root, f'gpt_webtext_{seq_len}.pt')
>         else:
>             encoded_data_cache_path = f'gpt_webtext_{seq_len}.pt'
> 
>         self.data = torch.randint(0,10000,(seq_len, ), requires_grad=False, device=torch.device('cpu')).long()
>         self.attention_mask = (torch.rand((seq_len, seq_len), requires_grad=False, device=torch.device('cpu')))
>         self.attention_mask = torch.where(self.attention_mask < 0.5, 0, 1)
>         print("self.atttntion_mask:",self.attention_mask[:20])
>         
>         self.mbs =mbs 
>         print("self.mbs:",self.mbs)
> 
>         torch.save((seq_len, self.data, self.attention_mask), encoded_data_cache_path)
> 
>     def __len__(self):
>         print("WebtextDataset,self.mbs*3:",self.mbs) ## len(train_loader) ：返回的是len(dataset)/batch_size
>         return self.mbs * 5
> 
>     def __getitem__(self, index):
>         return {'input_ids':self.data,
>             'attention_mask': self.attention_mask[0]}, self.data
> ```
> 
> I run this model and colossalai just spends 1s for 1 iteration. But I run the same model on Megatron-LM and I need about 100s for one iteration.
> 
> ### Environment
> _No response_

**Comment by feifeibear** [comment]
Currently, a config file is not necessary. See this as the latest CAI GPT example
https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/gpt/README.md

**Comment by lambda7xx** [comment]
> 

if I want to add parallel parallelism and sequence parallelism(SP) on the gpt, how should I run the code? I am confused by the different code and different document. And [your code](https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/gpt/README.md) seems  tensor parallelism. BTW, I talk with your colleague and he told me the SP  can not    combined with TP.

**Comment by lambda7xx** [comment]
> 

this code still has bug. AttributeError: 

```

Traceback (most recent call last):
  File "train_gpt_demo.py", line 241, in <module>
    main()
  File "train_gpt_demo.py", line 198, in main
    model = gpt2_medium(checkpoint=True)
  File "train_gpt_demo.py", line 102, in gpt2_medium
    return GPTLMModel(hidden_size=1024, num_layers=24, num_attention_heads=16, checkpoint=checkpoint)
  File "/python3.8/site-packages/colossalai/utils/model/utils.py", line 54, in wrapper
    f(module, *args, **kwargs)
  File "train_gpt_demo.py", line 74, in __init__
    self.model.gradient_checkpointing_enable()
  File "/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2LMHeadModel' object has no attribute 'gradient_checkpointing_enable'
Traceback (most recent call last):
  File "train_gpt_demo.py", line 241, in <module>
    main()
  File "train_gpt_demo.py", line 198, in main
    model = gpt2_medium(checkpoint=True)
  File "train_gpt_demo.py", line 102, in gpt2_medium
    return GPTLMModel(hidden_size=1024, num_layers=24, num_attention_heads=16, checkpoint=checkpoint)
  File "/.local/lib/python3.8/site-packages/colossalai/utils/model/utils.py", line 54, in wrapper
    f(module, *args, **kwargs)
  File "train_gpt_demo.py", line 74, in __init__
    self.model.gradient_checkpointing_enable()
  File "/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2LMHeadModel' object has no attribute 'gradient_checkpointing_enable'
Traceback (most recent call last):
  File "train_gpt_demo.py", line 241, in <module>
    main()
  File "train_gpt_demo.py", line 198, in main
    model = gpt2_medium(checkpoint=True)
  File "train_gpt_demo.py", line 102, in gpt2_medium
    return GPTLMModel(hidden_size=1024, num_layers=24, num_attention_heads=16, checkpoint=checkpoint)
  File "/.local/lib/python3.8/site-packages/colossalai/utils/model/utils.py", line 54, in wrapper
    f(module, *args, **kwargs)
  File "train_gpt_demo.py", line 74, in __init__
    self.model.gradient_checkpointing_enable()
  File "/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2LMHeadModel' object has no attribute 'gradient_checkpointing_enable'
Traceback (most recent call last):
  File "train_gpt_demo.py", line 241, in <module>
    main()
  File "train_gpt_demo.py", line 198, in main
    model = gpt2_medium(checkpoint=True)
  File "train_gpt_demo.py", line 102, in gpt2_medium
    return GPTLMModel(hidden_size=1024, num_layers=24, num_attention_heads=16, checkpoint=checkpoint)
  File "/.local/lib/python3.8/site-packages/colossalai/utils/model/utils.py", line 54, in wrapper
    f(module, *args, **kwargs)
  File "train_gpt_demo.py", line 74, in __init__
    self.model.gradient_checkpointing_enable()
  File "/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT2LMHeadModel' object has no attribute 'gradient_checkpointing_enable'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15959) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())

```

**Comment by feifeibear** [comment]
He is right, SP and TP can not work together :(
